FSC\HateoasBundle\Model\Link:
    properties:
        rel:
            xml_attribute: true
        href:
            xml_attribute: true
        templated:
        	xml_attribute: true
        	type: boolean